Implement DELETE, POST handling, update README
dbcloud-sdc/comments-section pull request #10
Opened 2019-03-13 00:06 UTC by pafrias

Allow config file to work with environment variables, so that
config doesn't have to simply be ignored, could potentially work
with unconfigured mysql servers for testing, and can be more easily
deployed on AWS

Redis has been removed after not significantly improving response times

2019-03-13 23:21 UTC, sharmoo requested changes

2019-03-13 23:21 UTC, sharmoo commented on README.md
>      * [GET /song/:songId/commentCount](#get-songsong_idcommentcount)
are we conforming to api/song/:songId/.... ?
as per conversation this morning

2019-03-13 23:21 UTC, sharmoo commented on app/controllers/router.js
> +    await db.readComments(songId)
why are you using async inside your get?
as a sidenote, post does not have this.

2019-03-13 23:21 UTC, sharmoo commented on app/helpers/config.js
> +};
this is more of a curiosity, but why are you specifying connection limits and timeouts? do you have to or this is providing some optimal functionality?

2019-03-13 23:21 UTC, sharmoo commented on app/models/mariadb.js
> +    let validate;
"let validate;"
....? then, no further use? I might be missing something?

2019-03-13 23:21 UTC, sharmoo commented on app/models/setup.sql
>    followers INT,
why is id allowed to be null. also what if user posts a comment? where does the id come from?

2019-03-13 23:21 UTC, sharmoo commented on index.js
> +const morgan = require('morgan');
Hopefully, you have removed morgan in your ec2 instance(s). This will slow your tests down horribly (MaMa was doing this and removal of morgan alone resulted in at least 300% query speed improvement).

2019-03-13 23:21 UTC, sharmoo commented on index.js
>  app.use(compress());
how much improvement have you seen from compression? out of curiosity.

2019-03-13 23:21 UTC, sharmoo commented on index.js
why are you sending a loaderfile....?

2019-03-13 23:21 UTC, sharmoo commented on index.js
>  });
what's with the res.sendFile??

2019-03-14 00:26 UTC, pafrias commented on app/controllers/router.js
> +    await db.readComments(songId)
It was an experiment to see if it improved performance. Sadly, it did not

2019-03-14 00:30 UTC, pafrias commented on README.md
>      * [GET /song/:songId/commentCount](#get-songsong_idcommentcount)
I'm sorry, my README is not up to date

2019-03-14 00:30 UTC, sharmoo commented on app/controllers/router.js
> +    await db.readComments(songId)
okay

2019-03-14 00:33 UTC, pafrias commented on app/models/mariadb.js
> +    let validate;
If an arrow function returns a promise with no other variable definitions, ESLINT will automatically remove the curly brackets from the function and move the first promise to the top of the arrow function.

As I intend to validate my messages before insertion in the future, this placeholder both reminds me of that and keeps the braces intact.

2019-03-14 00:33 UTC, pafrias commented on app/models/setup.sql
>    followers INT,
Primary keys can never be null

2019-03-14 00:34 UTC, pafrias commented on index.js
> +const morgan = require('morgan');
Morgan is removed, it is left in the comment here so that it need not be typed out in future debugging.

2019-03-14 00:34 UTC, pafrias commented on index.js
>  app.use(compress());
A lot.

2019-03-14 00:34 UTC, pafrias commented on index.js
Because loader requires it for testing, you are also serving it somehow.

2019-03-14 00:34 UTC, pafrias commented on index.js
>  });
It is a more specific path.

2019-03-14 00:36 UTC, sharmoo commented on app/models/setup.sql
>    followers INT,
ah, I did not see the primary key addition at the bottom

2019-03-14 00:38 UTC, sharmoo submitted a review, later dismissed

2019-03-14 02:15 UTC, sharmoo approved these changes

2019-03-14 02:16 UTC, merged